### ISSUE TITLE
Keyboard behaviour not working properly

### ISSUE THREAD

**Issue by rodneyrod** [modulebaan/harbour-sailbook#15]
When tapping outside of a text field or after submitting a text field, the keyboard sometimes stays open.

Also, the dictionary on the keyboard doesn't show at all.

**Comment by modulebaan** [comment]
Dictionary isn't something I can fix if there's an issue since this is all Jolla his stuff. 

I don't know where you have this behavior but I can't reproduce this issue. Try to restart your keyboard with Sailfish Utilities.

Which device do you use?

**Comment by modulebaan** [comment]
Dictionary isn't supported by Jolla in Webviews.
We're rebuilding Sailbook now and may fix your keyboard focus issue.
